---
- name: Add APT key for Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add Grafana APT repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: "{{ service }}"

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Grafana package
  apt:
    name: "{{ service }}"
    state: present